language: php
php:
  - '8.0'
  - '8.1'
install:
  - composer install
script:
  - mkdir temp
  - mkdir log
  - chmod -R a+rw temp log
  - vendor/bin/phpstan analyse app www --level 8
  - vendor/bin/phpunit .